<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etudiant extends \App\Entity\Etudiant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'dateNaiss', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'mobile', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'numRue', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'rue', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'copos', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'cheminPhoto', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'specialite', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'rPs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'dateNaiss', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'mobile', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'numRue', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'rue', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'copos', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'cheminPhoto', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'specialite', '' . "\0" . 'App\\Entity\\Etudiant' . "\0" . 'rPs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etudiant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaiss(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaiss', []);

        return parent::getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaiss(?\DateTimeInterface $dateNaiss): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaiss', [$dateNaiss]);

        return parent::setDateNaiss($dateNaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile(?string $mobile): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(?string $sexe): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRue', []);

        return parent::getNumRue();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRue(?string $numRue): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRue', [$numRue]);

        return parent::setNumRue($numRue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRue', []);

        return parent::getRue();
    }

    /**
     * {@inheritDoc}
     */
    public function setRue(?string $rue): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRue', [$rue]);

        return parent::setRue($rue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopos', []);

        return parent::getCopos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopos(?string $copos): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopos', [$copos]);

        return parent::setCopos($copos);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminPhoto', []);

        return parent::getCheminPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminPhoto(?string $cheminPhoto): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminPhoto', [$cheminPhoto]);

        return parent::setCheminPhoto($cheminPhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotion(): ?\App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotion', []);

        return parent::getPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotion(?\App\Entity\Promotion $promotion): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotion', [$promotion]);

        return parent::setPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?\App\Entity\Niveau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(?\App\Entity\Niveau $niveau): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite(): ?\App\Entity\Specialite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', []);

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(?\App\Entity\Specialite $specialite): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', [$specialite]);

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getRPs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRPs', []);

        return parent::getRPs();
    }

    /**
     * {@inheritDoc}
     */
    public function addRP(\App\Entity\RP $rP): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRP', [$rP]);

        return parent::addRP($rP);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRP(\App\Entity\RP $rP): \App\Entity\Etudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRP', [$rP]);

        return parent::removeRP($rP);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbActivites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbActivites', []);

        return parent::getNbActivites();
    }

}
