index:
    path: /
    controller: App\Controller\SecurityController::index

############ routes accès public ############
accueil_global:
    path: /
    controller: App\Controller\SecurityController::login

inscription:
    path: /inscription
    controller: App\Controller\RegisterController::addUserEtudiant

confirmMail:
    path: /confirmMail/{token}
    controller: App\Controller\RegisterController::confirmMail

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

login_success:
    path: /login_success
    controller: App\Controller\SecurityController::home


###### Routes etudiant############
# Consultation /Edition d'un étudiant
showEditEtudiant:
  path: /etudiant/showEdit
  controller: App\Controller\EtudiantController::showEdit

# Page accueil étudiant : renvoie la liste des 7 dernières rp et des stages
etudiantHome:
  path: /etudiant/home
  controller: App\Controller\EtudiantController::home

#etudiantProfil:
  #path: /etudiant/monCompte
  #controller: App\Controller\EtudiantController::getEtudiant

#Liste les rps d'un étudiant connecté
etudiantRps:
  path: /etudiant/rps
  controller: App\Controller\EtudiantController::getLesRP

#Liste les rp archivées d'un étudiant connecté
etudiantRpsArchivees:
  path: /etudiant/rpsArchivees
  controller: App\Controller\EtudiantController::getLesRPArchivées

#etudiantRPByStatut:
  #path: /etudiant/rp/{idStatut}
  #controller: App\Controller\EtudiantController::getLesRPByStatut
  
#Liste les rp d'un étudiant
#rpByEtudiant:
  #path: /getLesRPByEtudiant/{$idEtudiant}
  #controller: App\Controller\RpController::getLesRPByEtudiant

#Liste les rp d'un étudiant et par statut
#rpByEtudiantByStatut:
  #path: /getLesRPByEtudiantByStatut/{idEtudiant}/{idStatut}
  #controller: App\Controller\RpController::getLesRPByEtudiantByStatut

#Permet de consulter et d'éditer, d'ajouter une rp
rpShowEditAdd:
  path: /rp/showEditAdd/{idRp<\d+>?0}
  controller: App\Controller\RpController::showEditAdd

#Permet d'archiver une rp
rpArchiver:
  path: /rp/archiver/{idRp<\d+>?0}
  controller: App\Controller\RpController::archiver

#Permet de désarchiver une rp
rpDesarchiver:
  path: /rp/desarchiver/{idRp<\d+>?0}
  controller: App\Controller\RpController::desarchiver

#Liste les activités d'une rp passée en paramètre
rpActiviteList:
  path: /rp/activite/list/{idRp<\d+>?0}
  controller: App\Controller\RpActiviteController::rpActiviteList

#Edite une activité dont l'id est passé en paramètre
rpActiviteEdit:
  path: /rp/activite/edit/{idRpActivite<\d+>?0}
  controller: App\Controller\RpActiviteController::rpActiviteEdit

#Permet d'ajouter une activité dont l'id rp est passé en paramètre
rpActiviteAdd:
  path: /rp/activite/add/{idRp<\d+>?0}
  controller: App\Controller\RpActiviteController::rpActiviteAdd

#Permet de supprimer une activité dont l'id est passée en paramètre
rpActiviteRemove:
  path: /rp/activite/remove/{idRpActivite<\d+>?0}
  controller: App\Controller\RpActiviteController::rpActiviteRemove

#Liste les productions d'une rp passée en paramètre
rpProductionList:
  path: /rp/production/list/{idRp<\d+>?0}
  controller: App\Controller\RpProductionController::rpProductionList

#Permet d'ajouter une production à une rp
rpProductionAdd:
  path: /rp/production/add/{idRp<\d+>?0}
  controller: App\Controller\RpProductionController::rpProductionAdd

#Permet d'éditer la production d'une rp
rpProductionEdit:
  path: /rp/production/edit/{idProduction<\d+>?0}
  controller: App\Controller\RpProductionController::rpProductionEdit

#Permet de supprimer une production dont l'id est passée en paramètre
rpProductionRemove:
  path: /rp/production/remove/{idProduction<\d+>?0}
  controller: App\Controller\RpProductionController::rpProductionRemove


#Liste les commentaires d'une rp passée en paramètre
rpCommentaireList:
  path: /rp/commentaire/list/{idRp<\d+>?0}
  controller: App\Controller\RpCommentaireController::rpCommentaireList

#Permet à l'étudiant de soumettre sa rp à un enseignant
rpCommentaireNotifierEnseignant:
  path: /rp/commentaire/notifierEnseignant/{idRp<\d+>?0}
  controller: App\Controller\RpCommentaireController::rpNotifier

#etudiantRps:
  #path: /etudiant/rps
  #controller: App\Controller\EtudiantController::getLesRP



#Liste les stages  d'un étudiant connecté
etudiantStages:
  path: /etudiant/stages
  controller: App\Controller\StageController::getLesStagesByEtudiant
  
#Permet à un étudiant connecté d'ajouter ou de modifier un stage
stageAddEdit:
  path: etudiant/stage/add/{idStage<\d+>?0}
  controller: App\Controller\StageController::addEdit


#Permet à un étudiant connecté de renseigner sa semaine de stage en ajoutant des taches
showEditSemaineStage:
    path: etudiant/stage/showEditSemaineStage/{idStage<\d+>?0}/{numSemaine<\d+>?0}
    controller: App\Controller\StageController::showEditSemaineStage

#suppression d'une tache
removeTache:
  path: /etudiant/stage/tache/removeTache/{idTache}
  controller: App\Controller\TacheSemaineController::remove

#suppression d'une tache
editTache:
  path: /etudiant/stage/tache/editTache/{idTache}
  controller: App\Controller\TacheSemaineController::editTache



##################################################################################
###### Routes enseignant ############
###################################################################################
enseignantHome:
  path: /enseignant/home
  controller: App\Controller\EnseignantController::home

showRp:
  path: /enseignant/rp/show/{idRp}
  controller: App\Controller\RpController::show

# liste les promotions en cours
listPromos:
  path: /enseignant/promo/list/
  controller: App\Controller\PromotionController::list

# liste les rp d'une promo en cours (slam1, sisr2)
# La variable $source permet de savoir sur quel lien on a cliqué déclencher cette fonction
# si $source=menu, on vient du menu de gauche et on affiche la liste de toutes les rp des etudiants de la spé et du niveau
# $source=tb, on affiche le tableau de bord (home enseignant) et on affiche les étudiant avec la liste des etudiants, le nb de rp, le nb de stage
listEtudiantsParPromo:
  path: /enseignant/promo/etudiants/list/{idSpecialite}/{idNiveau}/{source}
  controller: App\Controller\PromotionController::listEtudiantsParPromo
 
# Permet à l'enseignant d'ajouter un commentaire
# On met le champ enseignant de la rp à null
# On change le statut de la rp pour le mettre à commentée
addCommentaireRp:
  path: /enseignant/rp/commentaire/add/{idRp}
  controller: App\Controller\RpCommentaireController::addCommentaire

# Liste les rp d'un étudiant
listRpParEtudiant:
  path: /enseignant/etudiant/rp/list/{idEtudiant}
  controller: App\Controller\RpController::listParEtudiant

# Liste toutes les RP non archivées
# classées par promo et par étudiant
listToutesLesRpPromosEnCours:
  path: /enseignant/rp/list/{idSpecialite}
  controller: App\Controller\EnseignantController::listRp

# Permet de valider une rp
validerRp:
  path: /enseignant/rp/valider/{idRp<\d+>?0}
  controller: App\Controller\RpController::valider

showEditEnseignant:
  path: /enseignant/showEdit
  controller: App\Controller\EnseignantController::showEdit

listRpsArchivees:
  path: /enseignant/listRpsArchivees
  controller: App\Controller\EnseignantController::listRpsArchivees


#Liste des stages des étudiants dont l'enseignant assure le suivi
listeStagesSuivis:
  path: /enseignant/stages
  controller: App\Controller\StageController::getLesStagesSuivis

#consultation d'un stage dont l'enseignant assure le suivi
showStage:
  path: /enseignant/stage/show/{idStage}
  controller: App\Controller\StageController::showStage

#consultation de l'activité d'une semaine de stage d'un étudiant
showSemaineStage:
  path: /enseignant/stage/semaine/show/{idStage}/{numSemaine}
  controller: App\Controller\SemaineStageController::showSemaine

# Liste les stages d'un étudiant (depuis le tableau de bord)
listStagesByEtudiant:
  path: /enseignant/stage/listStagesByEtudiant/{idEtudiant}
  controller: App\Controller\StageController::listStagesByEtudiant


###### Routes admin ############

adduserEnseignant:
  path: /admin/addUserEnseignant
  controller: App\Controller\AdminController::addUserEnseignant

listEnseignants:
  path: /admin/listEnseignants
  controller: App\Controller\AdminController::listEnseignants

showEditEnseignantAdmin:
  path: /admin/showEditEnseignant/{idUser}
  controller: App\Controller\AdminController::showEditEnseignant

listPromoEtudiants:
  path: /admin/listPromoEtudiants
  controller: App\Controller\AdminController::listPromoEtudiants

showEditEtudiantAdmin:
  path: /admin/showEditEtudiant/{idEtudiant}
  controller: App\Controller\AdminController::showEditEtudiant

#Permet de lister les comptes des étudiants qui n'ont pas encore été activés
listerComptesNonActifs:
  path: /admin/listerComptesNonActifs
  controller: App\Controller\AdminController::listerComptesNonActifs

#Permet de valider un compte étudiant (passer le statut user de AR à AC)
validerCompte:
  path: /admin/validerCompte/{email}
  controller: App\Controller\AdminController::validerCompte

#Permet de supprimer un compte étudiant
supprimerCompte:
  path: /admin/supprimerCompte/{email}
  controller: App\Controller\AdminController::supprimerCompte