<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnZFxJc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnZFxJc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFnZFxJc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFnZFxJc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFnZFxJc\App_KernelDevDebugContainer([
    'container.build_hash' => 'FnZFxJc',
    'container.build_id' => '361bd742',
    'container.build_time' => 1645368146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnZFxJc');
