<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6XxrKz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6XxrKz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6XxrKz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6XxrKz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT6XxrKz\App_KernelDevDebugContainer([
    'container.build_hash' => 'T6XxrKz',
    'container.build_id' => 'c5456aa4',
    'container.build_time' => 1639558796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6XxrKz');
